import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { IBook } from "@/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Footer() {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/book`, {
    cache: "force-cache",
  });
  if (!response.ok) {
    return (
      <footer className="pt-2">
        <div className="bottom-0 pt-4 pb-4 font-bold text-gray-500 h-14 w-auto lg:w-[70%] ">
          copyright @koiforever
        </div>
      </footer>
    );
  }
  const books: IBook[] = await response.json();
  const bookCount = books.length;
  return (
    <footer className="pt-2">
      <div className="bottom-0 font-bold text-gray-500 h-16 w-auto lg:w-[70%] ">
        copyright @koiforever
        <br />
        <span className="text-gray-400 text-sm">
          {bookCount} 개의 도서가 등록되어 있습니다.
        </span>
      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <div className="container w-auto lg:w-[70%] bg-white h-full m-auto p-4 shadow-gray-500">
          <header className="h-16 font-bold text-lg leading-[64px]">
            <Link href={"/"}>📚 Books</Link>
          </header>
          <main className="pt-3 pb-4">{children}</main>
          <Footer />
        </div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
